info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework: DEBUG
management:
  security:
    enabled: false
spring:
  application:
    name: composite
  cloud:
    config:
      server:
        git:
          uri: https://proxyuser:proxypassword@github.com/ojhughes/config-source-2
          proxy:
            http:
              host: proxy-noauth.rgb.springapps.io
              port: 3128
              username: proxyuser
              password: proxypassword
            https:
              host: proxy-auth.rgb.springapps.io
              port: 3128
              username: proxyuser
              password: proxypassword
          clone-on-start: true
  profiles:
    active: git
server:
  port: 8888
